# Generated by Django 5.0.4 on 2024-05-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=256)),
                ('owner_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('html_url', models.CharField(max_length=250)),
                ('avathar_url', models.CharField(max_length=250)),
                ('stars_count', models.IntegerField()),
                ('forks_count', models.IntegerField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
