# Generated by Django 5.0.4 on 2024-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='language',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
